name: Test Dependabot Updates

on:
  pull_request:
    branches:
      - main
    paths:
      - "package.json"
      - "packages/**/package.json" # Monitor all package.json files

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18] # Test across multiple Node.js versions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install
          if [ -f "packages/api/package.json" ]; then cd packages/api && npm install && cd ../..; fi
          if [ -f "packages/frontend/package.json" ]; then cd packages/frontend && npm install && cd ../..; fi

      - name: Run Tests
        run: |
          npm test || echo "No tests in root"
          if [ -f "packages/api/package.json" ]; then cd packages/api && npm test && cd ../..; fi
          if [ -f "packages/frontend/package.json" ]; then cd packages/frontend && npm test && cd ../..; fi
